In [1]:
import pandas as pd
import numpy as np

In [2]:
Data=pd.ExcelFile('Data.xlsx')
Data.sheet_names

['Demographics',
 'Store Mapping',
 'Category Mapping',
 'Ping_Information',
 'Variable Descriptions']

In [3]:
Demo = pd.read_excel(Data,'Demographics')
Store_map = pd.read_excel(Data,'Store Mapping')
Category_map = pd.read_excel(Data,'Category Mapping')
Ping_info = pd.read_excel(Data,'Ping_Information')
Variable_Desc = pd.read_excel(Data,'Variable Descriptions')

In [4]:
Store_map.head(100)

,Unnamed: 0,Store_Name,Floor_name,Floor_Index,latitude,longitude
0,NaN,Jamba Juice,Concourse Level,0,37.784091,-122.406813
1,NaN,Coriander Gourmet Thai,Concourse Level,0,37.784596,-122.406210
2,NaN,NYS Collection,Concourse Level,0,37.784396,-122.406587
3,NaN,Hallmark,Concourse Level,0,37.783771,-122.407377
4,NaN,Sorabol Korean BBQ & Asian Noodles,Concourse Level,0,37.784601,-122.406328
5,NaN,Pasta Moto,Concourse Level,0,37.784534,-122.406025
6,NaN,Abercrombie & Fitch,Concourse Level,0,37.783944,-122.407537
7,NaN,Fire of Brazil,Concourse Level,0,37.784447,-122.406224
8,NaN,ProActiv Solutions,Concourse Level,0,37.784161,-122.406900
9,NaN,Corner W,Concourse Level,0,37.784808,-122.406501
10,NaN,Buckhorn Grill,Concourse Level,0,37.784569,-122.406141
11,NaN,Cako Bakery,Concourse Level,0,37.784670,-122.406679
12,NaN,Claire's Boutique,Concourse Level,0,37.784126,-122.407061
13,NaN,Bristol Farms,Concourse Level,0,37.784159,-122.406350
14,NaN,PacSun,Concourse Level,0,37.783959,-122.406910
15,NaN,DAVIDsTEA,Concourse Level,0,37.784411,-122.406709
16,NaN,Andale Mexican Restaurant,Concourse Level,0,37.784511,-122.405956
17,NaN,Sunglass Hut,Concourse Level,0,37.784071,-122.406885
18,NaN,Peet's Coffee & Tea,Concourse Level,0,37.784591,-122.406782
19,NaN,Panda Express,Concourse Level,0,37.783778,-122.407161
20,NaN,GNC,Concourse Level,0,37.784053,-122.407307
21,NaN,New Era,Concourse Level,0,37.783893,-122.407389
22,NaN,LEGO,Concourse Level,0,37.784222,-122.406978
23,NaN,Mrs. Fields,Concourse Level,0,37.783953,-122.407318
24,NaN,Beard Papa's Cream Puffs,Concourse Level,0,37.784505,-122.406555
25,NaN,Ajisen Ramen,Concourse Level,0,37.783767,-122.407070
26,NaN,Shoe Palace,Concourse Level,0,37.784106,-122.407189
27,NaN,Loving Hut Vegan Cuisine,Concourse Level,0,37.784292,-122.406010
28,NaN,Ghirardelli Ice Cream and Chocolate Shop,Concourse Level,0,37.784449,-122.406665
29,NaN,Marbles: The Brain Store,Concourse Level,0,37.784353,-122.406773
...,...,...,...,...,...,...
70,NaN,Sunglass Hut,Level 1,1,37.784112,-122.406949
71,NaN,Timberland,Level 1,1,37.784884,-122.406486
72,NaN,Tourneau,Level 1,1,37.784610,-122.406886
73,NaN,Adidas,Level 1,1,37.784466,-122.406961
74,NaN,Superdry,Level 1,1,37.784470,-122.406760
75,NaN,Origins,Level 1,1,37.783730,-122.407061
76,NaN,Club Monaco Men,Level 1,1,37.783909,-122.407393
77,NaN,Currency Exchange International,Level 1,1,37.783810,-122.407336
78,NaN,Club Monaco Women,Level 1,1,37.783864,-122.406836
79,NaN,American Eagle Outfitters,Level 1,1,37.784188,-122.407159
80,NaN,Nordstrom E-Bar,Level 1,1,37.783827,-122.407024
81,NaN,Kiehl's,Level 1,1,37.784047,-122.407035
82,NaN,Tiffany & Co.,Level 1,1,37.784397,-122.406148
83,NaN,BOSS,Level 1,1,37.784185,-122.406379
84,NaN,Michael Kors Men,Level 1,1,37.784396,-122.406726
85,NaN,lululemon athletica,Level 2,2,37.784579,-122.406476
86,NaN,Coach,Level 2,2,37.783744,-122.407323
87,NaN,bareMinerals,Level 2,2,37.784515,-122.406218
88,NaN,Forever Flawless,Level 2,2,37.784024,-122.407272
89,NaN,OAK+FORT,Level 2,2,37.784139,-122.407183
90,NaN,Auntie Anne's Pretzels,Level 2,2,37.784341,-122.406785
91,NaN,Max & Co.,Level 2,2,37.784559,-122.406270
92,NaN,Onassis,Level 2,2,37.784136,-122.405805
93,NaN,Zara,Level 2,2,37.784705,-122.406568
94,NaN,bebe,Level 2,2,37.784142,-122.407420
95,NaN,ECCO,Level 2,2,37.784267,-122.406528
96,NaN,Lady Foot Locker,Level 2,2,37.784046,-122.406884
97,NaN,Cotton On,Level 2,2,37.784252,-122.406942
98,NaN,Pandora,Level 2,2,37.784387,-122.406732
99,NaN,The Body Shop,Level 2,2,37.783739,-122.407271

In [5]:
Category_map.head()

   Unnamed: 0         Store_Name Broad_Category    Fine_Category
0         NaN      Amazon Pop-Up         Retail            Misc.
1         NaN     Bespoke Events         Retail            Misc.
2         NaN  Bespoke Coworking         Retail  Specialty Store
3         NaN              Dyson         Retail            Misc.
4         NaN   Penhaligonï¿½Ûªs         Retail            Misc.

In [6]:
Ping_info.head()

,Unnamed: 0,Shopper_ID,floor,lat,lng,x,y,seenTimestamp
0,NaN,Shopper_556,Floor 4,37.661463,-122.298673,-2934.558251,-16169.722290,2016-11-22T02:16:06.000Z
1,NaN,Shopper_556,Floor 1,37.784062,-122.406943,117.262475,151.823812,2016-12-23T22:01:25.000Z
2,NaN,Shopper_556,Floor 4,37.784361,-122.406710,156.125087,171.357200,2016-11-22T01:42:28.000Z
3,NaN,Shopper_360,Concourse,37.784341,-122.406891,134.499673,167.674401,2016-10-13T18:27:38.000Z
4,NaN,Shopper_360,Floor 2,37.784017,-122.407307,94.981693,172.269243,2016-10-12T21:36:18.000Z

In [7]:
Store_map=Store_map.drop(['Unnamed: 0'],axis=1)
Category_map=Category_map.drop(['Unnamed: 0'],axis=1)
Ping_info=Ping_info.drop(['Unnamed: 0'],axis=1)

In [8]:
print(Ping_info.floor.unique())
print(Store_map.Floor_name.unique())
print(Store_map.Floor_Index.unique())

['Floor 4' 'Floor 1' 'Concourse' 'Floor 2' 'Floor 3']
['Concourse Level' 'Level 1' 'Level 2' 'Level 3' 'Level 4/N1' 'Level 5/N2'
 'N3' 'N4' 'N5']
[0 1 2 3 4 5 6 7 8]

In [9]:
di={'Floor 4': 4 ,'Floor 1': 1, 'Concourse': 0 ,'Floor 2': 2 ,'Floor 3': 3}
Ping_info["store_floor"]=Ping_info.floor
Ping_info.store_floor=Ping_info.store_floor.map(di)
Ping_info.head()

,Shopper_ID,floor,lat,lng,x,y,seenTimestamp,store_floor
0,Shopper_556,Floor 4,37.661463,-122.298673,-2934.558251,-16169.722290,2016-11-22T02:16:06.000Z,4
1,Shopper_556,Floor 1,37.784062,-122.406943,117.262475,151.823812,2016-12-23T22:01:25.000Z,1
2,Shopper_556,Floor 4,37.784361,-122.406710,156.125087,171.357200,2016-11-22T01:42:28.000Z,4
3,Shopper_360,Concourse,37.784341,-122.406891,134.499673,167.674401,2016-10-13T18:27:38.000Z,0
4,Shopper_360,Floor 2,37.784017,-122.407307,94.981693,172.269243,2016-10-12T21:36:18.000Z,2

In [10]:
i=0
# len(Ping_info)
# Ping_info.Shopper_ID[5]
# # Ping_info.store_floor[i]
# Ping_info.lat[0]
# i=1666
# latt=np.square((Ping_info.lat[i])-(Store_map[Store_map['Floor_Index'] == Ping_info.store_floor[i]].latitude))
# lngg=np.square((Ping_info.lng[i])-(Store_map[Store_map['Floor_Index'] == Ping_info.store_floor[i]].longitude))
# min_dist=np.sqrt(latt+lngg)
# np.argmin(min_dist)
# min(min_dist)
# # Store_map.Store_Name[int(min(dist))]
# # Store_map[Store_map['Floor_Index'] == Ping_info.store_floor[i]].latitude
Store_map[Store_map['Floor_Index'] == Ping_info.store_floor[i]].longitude

152   -122.406832
153   -122.406248
154   -122.406528
155   -122.405776
156   -122.406350
157   -122.406081
158   -122.407311
159   -122.405736
Name: longitude, dtype: float64

In [12]:
Nearest_shop=[]
Nearest_Distance=[]
for i in range(len(Ping_info)):
    latt=np.square((Ping_info.lat[i])-(Store_map[Store_map['Floor_Index'] == Ping_info.store_floor[i]].latitude))
    lngg=np.square((Ping_info.lng[i])-(Store_map[Store_map['Floor_Index'] == Ping_info.store_floor[i]].longitude))
    min_dist=np.sqrt(latt+lngg)
    Nearest_Distance.append(min(min_dist))
    Nearest_shop.append(Store_map.Store_Name[np.argmin(min_dist)])

In [13]:
Ping_info['Nearest_shop']=Nearest_shop
Ping_info['Nearest_Distance']=Nearest_Distance
Ping_info.head(200)

,Shopper_ID,floor,lat,lng,x,y,seenTimestamp,store_floor,Nearest_shop,Nearest_Distance
0,Shopper_556,Floor 4,37.661463,-122.298673,-2934.558251,-1.616972e+04,2016-11-22T02:16:06.000Z,4,Bloomingdale's,0.162571
1,Shopper_556,Floor 1,37.784062,-122.406943,117.262475,1.518238e+02,2016-12-23T22:01:25.000Z,1,Sunglass Hut,0.000050
2,Shopper_556,Floor 4,37.784361,-122.406710,156.125087,1.713572e+02,2016-11-22T01:42:28.000Z,4,TAP 415,0.000136
3,Shopper_360,Concourse,37.784341,-122.406891,134.499673,1.676744e+02,2016-10-13T18:27:38.000Z,0,Marbles: The Brain Store,0.000118
4,Shopper_360,Floor 2,37.784017,-122.407307,94.981693,1.722692e+02,2016-10-12T21:36:18.000Z,2,Forever Flawless,0.000036
5,Shopper_420,Floor 4,37.661624,-122.298459,-2908.686633,-1.617058e+04,2016-12-19T01:31:08.000Z,4,Bloomingdale's,0.162591
6,Shopper_420,Floor 1,37.783856,-122.407092,91.860575,1.446519e+02,2016-12-19T01:36:10.000Z,1,Nordstrom E-Bar,0.000074
7,Shopper_245,Floor 2,37.783970,-122.407194,98.389647,1.615519e+02,2016-10-14T03:02:55.000Z,2,Forever Flawless,0.000095
8,Shopper_334,Floor 2,37.783828,-122.406986,100.307150,1.374774e+02,2017-03-18T03:25:59.000Z,2,Dyson,0.000035
9,Shopper_205,Floor 1,37.784219,-122.406896,132.417939,1.613389e+02,2017-06-06T20:33:31.000Z,1,Swatch,0.000050
10,Shopper_205,Concourse,37.784638,-122.406411,187.674064,1.616688e+02,2017-06-06T01:28:51.000Z,0,Amoura Cafe Fresh Mediterranean,0.000014
11,Shopper_530,Floor 1,35.085149,-113.663734,337611.758000,-7.520261e+05,2017-03-08T23:50:12.000Z,1,Bloomingdale's,9.149345
12,Shopper_530,Concourse,36.541271,-118.435462,152099.134600,-3.428527e+05,2017-01-28T00:07:15.000Z,0,Bloomingdale's,4.160234
13,Shopper_359,Concourse,37.783961,-122.407034,95.921172,1.463724e+02,2017-05-20T18:34:46.000Z,0,Haagen Dazs,0.000123
14,Shopper_189,Concourse,35.239976,-114.220990,314753.916500,-7.054506e+05,2017-01-17T23:56:19.000Z,0,Bloomingdale's,8.571017
15,Shopper_189,Concourse,37.784049,-122.407055,101.470762,1.545847e+02,2017-01-17T02:40:49.000Z,0,Claire's Boutique,0.000077
16,Shopper_189,Concourse,37.784084,-122.407044,104.863798,1.567499e+02,2017-01-17T01:57:58.000Z,0,Claire's Boutique,0.000045
17,Shopper_481,Floor 2,35.265054,-114.246672,315111.051200,-7.018778e+05,2017-04-11T22:10:26.000Z,2,Bloomingdale's,8.539075
18,Shopper_155,Floor 4,37.784287,-122.406954,135.207871,1.808558e+02,2017-06-13T17:38:20.000Z,4,TAP 415,0.000180
19,Shopper_155,Floor 1,36.980523,-119.811229,100136.465000,-2.233378e+05,2017-06-13T18:21:23.000Z,1,Bloomingdale's,2.716295
20,Shopper_155,Floor 4,37.759561,-122.385293,-491.224500,-3.102102e+03,2017-06-13T18:42:51.000Z,4,Bloomingdale's,0.031710
21,Shopper_287,Concourse,37.656648,-122.006913,15244.807110,-3.457726e+04,2017-04-13T04:10:15.000Z,0,Bloomingdale's,0.418673
22,Shopper_536,Floor 2,34.031987,-110.253652,469207.821200,-1.045435e+06,2017-06-12T18:34:39.000Z,2,Bloomingdale's,12.718149
23,Shopper_344,Floor 2,37.784028,-122.407106,108.378039,1.607393e+02,2017-01-24T21:49:27.000Z,2,OAK+FORT,0.000135
24,Shopper_41,Floor 2,33.504061,-108.734063,523281.103000,-1.180830e+06,2017-01-14T00:43:34.000Z,2,Bloomingdale's,14.325960
25,Shopper_41,Floor 3,37.783814,-122.407127,92.559116,1.435501e+02,2017-01-14T01:09:42.000Z,3,iPlay n Talk,0.000079
26,Shopper_122,Floor 4,36.066776,-116.842850,206531.372300,-4.821700e+05,2017-01-07T02:32:22.000Z,4,Bloomingdale's,5.821844
27,Shopper_51,Concourse,37.720868,-122.343518,-839.649368,-8.764928e+03,2017-05-14T01:33:11.000Z,0,Bloomingdale's,0.088591
28,Shopper_51,Floor 1,35.265134,-114.246611,315116.807500,-7.018766e+05,2016-10-13T19:57:16.000Z,1,Bloomingdale's,8.539312
29,Shopper_68,Floor 1,37.783840,-122.407236,81.628351,1.523024e+02,2017-02-03T17:50:55.000Z,1,Currency Exchange International,0.000104
...,...,...,...,...,...,...,...,...,...,...
170,Shopper_505,Concourse,34.005840,-110.166212,472635.864500,-1.052894e+06,2017-04-21T18:57:55.000Z,0,Bloomingdale's,12.809400
171,Shopper_129,Concourse,33.585966,-108.806016,525140.406400,-1.169911e+06,2016-10-25T20:42:26.000Z,0,Bloomingdale's,14.232927
172,Shopper_129,Floor 2,33.339215,-108.006549,556016.177100,-1.238683e+06,2016-10-25T20:46:05.000Z,2,Bloomingdale's,15.069617
173,Shopper_129,Concourse,37.715536,-122.186629,8573.358309,-1.884592e+04,2017-02-07T22:17:26.000Z,0,Bloomingdale's,0.229566
174,Shopper_129,Floor 4,33.061419,-107.106511,567695.536500,-1.326209e+06,2016-10-25T20:44:59.000Z,4,Bloomingdale's,16.011471
175,Shopper_425,Floor 1,37.028293,-119.958399,94637.926210,-2.104913e+05,2017-01-24T20:39:04.000Z,1,Bloomingdale's,2.561582
176,Shopper_425,Floor 2,34.315920,-111.249262,428953.891700,-9.616373e+05,2016-12-31T00:20:36.000Z,2,Bloomingdale's,11.683108
177,Shopper_425,Floor 2,33.585933,-108.806203,525139.264500,-1.169899e+06,2016-12-31T00:20:13.000Z,2,Bloomingdale's,14.232769
178,Shopper_425,Floor 1,37.783824,-122.407061,91.330745,1.401610e+02,2017-01-22T19:34:49.000Z,1,Nordstrom E-Bar,0.000037
179,Shopper_306,Floor 4,37.731723,-122.360248,-1156.024183,-6.839415e+03,2017-02-17T21:52:22.000Z,4,Bloomingdale's,0.069147
180,Shopper_106,Concourse,37.784024,-122.407242,87.718840,1.641310e+02,2017-01-13T21:05:36.000Z,0,GNC,0.000071
181,Shopper_10,Floor 2,34.486865,-111.724967,412468.595700,-9.188020e+05,2017-01-10T22:25:11.000Z,2,Bloomingdale's,11.178123
182,Shopper_10,Floor 4,37.784537,-122.406549,179.948476,1.750439e+02,2017-01-10T22:41:17.000Z,4,TAP 415,0.000306
183,Shopper_10,Floor 4,37.752279,-122.378446,-646.939671,-4.098182e+03,2017-01-10T22:59:29.000Z,4,Bloomingdale's,0.041694
184,Shopper_10,Floor 4,37.024614,-119.945207,91468.638170,-2.132109e+05,2017-01-10T22:31:20.000Z,4,Bloomingdale's,2.574989
185,Shopper_309,Floor 1,37.783936,-122.407246,88.487584,1.604202e+02,2016-10-31T23:31:58.000Z,1,Club Monaco Men,0.000150
186,Shopper_299,Floor 1,37.783947,-122.407152,95.248261,1.555801e+02,2017-01-04T23:58:17.000Z,1,Kiehl's,0.000154
187,Shopper_299,Floor 3,37.783984,-122.407157,104.088986,1.587957e+02,2017-01-05T00:22:46.000Z,3,iPlay n Talk,0.000141
188,Shopper_299,Concourse,37.784711,-122.408305,74.703514,2.840295e+02,2017-01-04T23:35:27.000Z,0,Starbucks,0.000918
189,Shopper_299,Floor 2,36.434618,-118.035370,168867.632900,-3.759328e+05,2017-01-04T21:43:56.000Z,2,Bloomingdale's,4.573963
190,Shopper_299,Concourse,37.729880,-122.352610,-707.256095,-7.490880e+03,2017-01-04T23:30:38.000Z,0,Bloomingdale's,0.075790
191,Shopper_285,Floor 3,37.198269,-120.737475,57774.306830,-1.495658e+05,2017-04-20T17:37:26.000Z,3,Bloomingdale's,1.767888
192,Shopper_285,Floor 2,37.727874,-122.225291,7124.261364,-1.548325e+04,2017-04-20T01:45:44.000Z,2,Bloomingdale's,0.188995
193,Shopper_350,Concourse,37.757704,-122.383922,-501.487427,-3.357730e+03,2016-12-23T23:48:53.000Z,0,Bloomingdale's,0.034109
194,Shopper_73,Floor 1,37.712435,-122.175269,9051.355185,-1.978802e+04,2017-03-14T02:26:01.000Z,1,Bloomingdale's,0.241548
195,Shopper_506,Floor 2,34.877587,-112.991232,363577.527300,-8.098777e+05,2016-12-18T20:04:51.000Z,2,Bloomingdale's,9.852946
196,Shopper_544,Concourse,37.784638,-122.406411,187.674064,1.616688e+02,2017-01-25T20:02:06.000Z,0,Amoura Cafe Fresh Mediterranean,0.000014
197,Shopper_544,Concourse,37.784638,-122.406411,187.674064,1.616688e+02,2017-01-25T19:57:16.000Z,0,Amoura Cafe Fresh Mediterranean,0.000014
198,Shopper_544,Floor 1,33.108763,-107.268448,584299.729500,-1.302390e+06,2016-12-27T00:03:15.000Z,1,Bloomingdale's,15.843056
199,Shopper_133,Concourse,37.784094,-122.407120,100.879926,1.621926e+02,2016-11-10T18:29:24.000Z,0,Champs Sports,0.000022

In [14]:
df_category=Category_map[['Store_Name','Fine_Category']]
di=dict((i,j) for i,j in zip(df_category.Store_Name,df_category.Fine_Category))
Ping_info['Fine_Category']=Ping_info.Nearest_shop.map(di)

In [15]:
Ping_info.head()

,Shopper_ID,floor,lat,lng,x,y,seenTimestamp,store_floor,Nearest_shop,Nearest_Distance,Fine_Category
0,Shopper_556,Floor 4,37.661463,-122.298673,-2934.558251,-16169.722290,2016-11-22T02:16:06.000Z,4,Bloomingdale's,0.162571,Department Stores
1,Shopper_556,Floor 1,37.784062,-122.406943,117.262475,151.823812,2016-12-23T22:01:25.000Z,1,Sunglass Hut,0.000050,Apparel And Accessories
2,Shopper_556,Floor 4,37.784361,-122.406710,156.125087,171.357200,2016-11-22T01:42:28.000Z,4,TAP 415,0.000136,Qsr Restaurants
3,Shopper_360,Concourse,37.784341,-122.406891,134.499673,167.674401,2016-10-13T18:27:38.000Z,0,Marbles: The Brain Store,0.000118,Toy Stores
4,Shopper_360,Floor 2,37.784017,-122.407307,94.981693,172.269243,2016-10-12T21:36:18.000Z,2,Forever Flawless,0.000036,Furniture And Decor

In [17]:
# top_visited_shop=[]
# top_visited_fine_cat=[]
# Shopper_ID=Ping_info.Shopper_ID.unique()
# for i in Ping_info.Shopper_ID.unique():
#     top_visited_shop.append(np.argmax(Ping_info[Ping_info.Shopper_ID ==i].Nearest_shop.value_counts(ascending=False)))
#     top_visited_fine_cat.append(np.argmax(Ping_info[Ping_info.Shopper_ID ==i].Fine_Category.value_counts(ascending=False)))

In [18]:
# di={'Shopper_ID':Shopper_ID,'top_visited_shop':np.array(top_visited_shop),'top_visited_fine_cat':np.array(top_visited_fine_cat)}
# top_visited_shop_map=pd.DataFrame(di)
# top_visited_shop_map

In [ ]:
# Ping_info=Ping_info.groupby('Shopper_ID')
# Ping_info